version: "3"
services:
  app:
    build: .
    volumes:
      - /home/rc/caliban-toolbox/caliban_toolbox:/usr/local/lib/python3.5/dist-packages/caliban-toolbox/
      - /home/rc/caliban-toolbox/notebooks:/notebooks
      - /deepcell_data:/data
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 93:8888

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dcdatasets
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw
      - ./mongo-data:/data/db
    ports:
      - 8081:8081
    command: mongod --auth
